### ISSUE TITLE
TypeError: unhashable type: 'EscapedString' in timingGetTimingSense

### ISSUE THREAD

**Issue by ARandomOWL** [ARandomOWL/liberty-to-genlib#7]
```
Traceback (most recent call last):
  File "/home/adrian/src/liberty-to-genlib/liberty-to-genlib.py", line 144, in <module>
    if not cellIsUnate(cell):
  File "/home/adrian/src/liberty-to-genlib/liberty-to-genlib.py", line 54, in cellIsUnate
    cell_sense = cellTimingSense(cell)
  File "/home/adrian/src/liberty-to-genlib/liberty-to-genlib.py", line 116, in cellTimingSense
    return outputpinTimingSense(output_pin)
  File "/home/adrian/src/liberty-to-genlib/liberty-to-genlib.py", line 102, in outputpinTimingSense
    timing_sense = timingGetTimingSense(timing)
  File "/home/adrian/src/liberty-to-genlib/liberty-to-genlib.py", line 93, in timingGetTimingSense
    return switcher.get(sense, TimingSense.NONE)
TypeError: unhashable type: 'EscapedString'
```

**Comment by ARandomOWL** [comment]
Fixed by 3ba23bf25d08cf88e58bf9839102f46c57c15251
